### ISSUE TITLE
OTAA_DHT11 sample doesn't compile

### ISSUE THREAD

**Issue by DeveloppeurPascal** [HelTecAutomation/ESP32_LoRaWAN#15]
/Users/pprem/Documents/Arduino/libraries/ESP32_LoRaWAN-master/examples/OTAA_DHT11/OTAA_DHT11.ino: In function 'void loop()':
OTAA_DHT11:179:28: error: no matching function for call to 'LoRaClass::DeviceStateInit()'
       LoRa.DeviceStateInit();
                            ^
In file included from /Users/pprem/Documents/Arduino/libraries/ESP32_LoRaWAN-master/examples/OTAA_DHT11/OTAA_DHT11.ino:46:0:
/Users/pprem/Documents/Arduino/libraries/ESP32_LoRaWAN-master/src/LoRa.h:87:8: note: candidate: void LoRaClass::DeviceStateInit(DeviceClass_t)
   void DeviceStateInit(DeviceClass_t CLASS);
        ^
/Users/pprem/Documents/Arduino/libraries/ESP32_LoRaWAN-master/src/LoRa.h:87:8: note:   candidate expects 1 argument, 0 provided
OTAA_DHT11:224:24: error: 'IsLowPowerOn' was not declared in this scope
       LoRa.DeviceSleep(IsLowPowerOn,DebugLevel);
                        ^
exit status 1
no matching function for call to 'LoRaClass::DeviceStateInit()'

**Comment by solotaker** [comment]
Hi:
I have fixed these issues.
Sorry, the DHT11 example has been in disrepair for a long time.
