### ISSUE TITLE
cannot get the EU_863_870 band to work

### ISSUE THREAD

**Issue by ASUK-Development** [HelTecAutomation/ESP32_LoRaWAN#18]
Hello, I am attempting to use my Wifi LORA 32 V2 (868-915 version) on the 868 band.

I saw this:

`#if defined( USE_BAND_868 )`

in lora.h so assumed defining this in my sketch this would have the desired effect but it stays on the 470 band. I am using the OTAA_OLED example. The comment by the license array seems to imply that the band could be derived from this which I obtained from the link in the Readme.

Could you advise me how to change to the 868 band?

**Comment by ASUK-Development** [comment]
I'm an idiot!

I changed the parameters in "Commissioning.h" and "LoRaMac-definitions.h" and it's working a treat.

**Comment by shmrymbd** [comment]
i cant find the file from this repo. pls advice
