### ISSUE TITLE
Frequency stays in 433

### ISSUE THREAD

**Issue by killengage** [HelTecAutomation/ESP32_LoRaWAN#2]
When loading the OTAA_OLED example the frequency stays on 433 in the serial. How to change to 868 ?

`00:25:11.639 -> Tx Freq:471100000
00:25:11.639 -> SSSSSS
00:25:16.185 -> First RxWindow Freq: 501500000
00:25:16.185 -> S1Tx delay time : 0162 ms
00:25:17.324 -> S
00:25:17.324 -> Second RxWindow Freq: 505300000
00:25:17.324 -> S
00:25:17.324 -> Tx Freq:470300000
00:25:17.324 -> S0S`

**Comment by Heltec-Aaron-Lee** [comment]
@killengage in file LoRaMac-definitions.h, you just need fix the USE_BAND_xxx into USE_BAND_868 is OK.

![default](https://user-images.githubusercontent.com/32860565/50320795-f8967d00-0508-11e9-963e-675fc50debf0.png)
