### ISSUE TITLE
Request: please add decoder code to OTAA_DHT11 example

### ISSUE THREAD

**Issue by holgerimbery** [HelTecAutomation/ESP32_LoRaWAN#30]
Please add the code for the decoder to the OTAA_DHT11 example, 
if it is already there please put the link in the sketch. 
This would help newbies (like me) to speed up learning

Example Decoder

function Decoder(bytes, port) {
  var input =(bytes.slice(0, 15));
  result = String.fromCharCode.apply(null, input);
  return {
      Sensor: result
  };
}

TNX

**Comment by onexecute** [comment]
Did this work for you? I'm having trouble making this work. For starters, I can not get the device to get data from the DHT11. When I use an online decoder on data: "VGVtcDowMCBIdW06MDAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==" all I get Temp:00 Hum:00%.

**Comment by holgerimbery** [comment]
obsolete - example was deleted without notice
