### ISSUE TITLE
I can't recive aby data from ttn

### ISSUE THREAD

**Issue by SiggiSigmann** [HelTecAutomation/ESP32_LoRaWAN#7]
I can connet to TheThingsNetwork via ABP only. But i can't reseave any Downlinks form the Network.

**Comment by Heltec-Aaron-Lee** [comment]
I thought you didn't correctly config the EUI, APPKEY etc.

**Comment by SiggiSigmann** [comment]
yes, sorry for this

**Comment by Heltec-Aaron-Lee** [comment]
That's no problem, shall close this topic now?
